### ISSUE TITLE
没有读取数据的接口啊

### ISSUE THREAD

**Issue by xxhong** [nebulasio/androidSDK#10]
老铁，没有合约读取数组的接口哦

**Comment by ChengOrangeJu** [comment]
这个是有的，可以通过queryTransferStatus的接口获取execute_result

**Comment by xxhong** [comment]
querypayinfo 这个接口在哪呢  确定提交了吗

**Comment by ChengOrangeJu** [comment]
@xxhong 是的，这个可以提供上链数据的返回。但是不上链的数据，类似api.call并没有接入

**Comment by xxhong** [comment]
什么时候能接入啊 急急急

**Comment by ym1808620172** [comment]
queryTransferStatus放回的execute_result 一直为“”没有数据。execute_result:""。是成功的交易

**Comment by donald99** [comment]
有了有了，赶紧拉代码
