### ISSUE TITLE
关于下载Nebulas官方钱包的问题

### ISSUE THREAD

**Issue by kumaleap** [nebulasio/androidSDK#9]
执行如下方法在部分手机上会跳转到指定的市场，但是你们没有在市场里上架这个app，导致用户根本无法下载，不知道去哪里下载，是否可以直接跳到浏览器里下载呢？我改了下，但是去官方找到的下载地址是跟版本号关联了，希望改正下 谢谢
private static void handleException(Context context) {
        Intent intent = new Intent(Intent.ACTION_VIEW);
        intent.setData(Uri.parse(String.format("market://details?id=%s", Constants.NAS_NANO_PACKAGE_NAME)));
        if (intent.resolveActivity(context.getPackageManager()) != null) {
            Toast.makeText(context, "没安装Nebulas智能数字钱包，请下载安装", Toast.LENGTH_SHORT).show();
            context.startActivity(intent);
        } else {
            intent.setData(Uri.parse(String.format("https://play.google.com/store/apps/details?id=%s", Constants.NAS_NANO_PACKAGE_NAME)));
            if (intent.resolveActivity(context.getPackageManager()) != null) {
                context.startActivity(intent);
            } else {
                Toast.makeText(context, "没安装应用市场或浏览器", Toast.LENGTH_SHORT).show();
            }
        }
    }

**Comment by donald99** [comment]
已处理，可pull code查看
